# Generated by Django 4.1.2 on 2024-05-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VahiclesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('carName', models.CharField(max_length=100)),
                ('CarModel', models.CharField(max_length=100)),
            ],
        ),
    ]
