# Generated by Django 4.1.2 on 2024-05-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vahiclesmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='vahiclesmodel',
            name='CarId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
