# Generated by Django 4.1.2 on 2024-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDetails', '0002_remove_vahiclesmodel_id_vahiclesmodel_carid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=100)),
                ('partImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
